apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/launch-stage: BETA
  name: hello-spa-oauth-sandbox
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/container-dependencies: "{client-app:[oauth-server]}"
    spec:
      containers:
      - image: $REGION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/client-app:latest
        name: client-app
        ports:
          - containerPort: 8000
        env:
        - name: REDIRECT_URI
          value: $REDIRECT_URI
        volumeMounts:
        - name: CLIENT_ID
          readOnly: true
          mountPath: /etc/secrets/clientid/
      - image: $REGION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/oauth-server:latest
        name: oauth-server
        env:
        - name: SITE_URL
          value: $SITE_URL
        - name: REDIRECT_URI
          value: $REDIRECT_URI
        - name: JWT_SECRET
          value: foobar
        volumeMounts:
        - name: CLIENT_ID
          readOnly: true
          mountPath: /etc/secrets/clientid/
        - name: CLIENT_SECRET
          readOnly: true
          mountPath: /etc/secrets/clientsecret/
      volumes:
      - name: CLIENT_ID
        secret:
          secretName: client_id_secret
          items:
          - key: latest
            path: clientid
      - name: CLIENT_SECRET
        secret:
          secretName: client_secret_secret
          items:
          - key: latest
            path: clientsecret
